const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const CLEAR_CART = "CLEAR_CART";
const EDIT_ITEM_FROM_CART = "EDIT_ITEM_FROM_CART";
export { ADD_TO_CART, REMOVE_FROM_CART, CLEAR_CART, EDIT_ITEM_FROM_CART };
